---
name: github
provider: github.com
repository: docker-tflint
url: https://github.com/cardboardci/docker-tflint
clone:
  ssh: git@github.com:cardboardci/docker-tflint.git
  https: https://github.com/cardboardci/docker-tflint.git