image: docker:latest

services:
  - docker:dind

stages:
  - Validate
  - Build
  - Test
  - Analyze
  - Release
  - Deploy

##
## Validate
##
shellcheck:
  stage: Validate
  image: koalaman/shellcheck:stable
  script:
    - bash .build/shellcheck.sh
    
# hadolint:
#   stage: Validate
#   image: hadolint/hadolint
#   script:
#     - apt-get update
#     - apt-get install -y shellcheck
#     - hadolint Dockerfile

# ##
# ## Build
# ##
# build:
#   stage: Build
#   script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#     - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .

# ##
# ## Test
# ##
# bats:
#   stage: Test
#   script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#     - echo "Run docker tests from bats"

# ##
# ## Analyze
# ##
# audit:
#   stage: Analyze
#   script: 
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#     - echo "Verify that all labels are applied to image"
#     - echo "Verify that the image is minimized"

# ##
# ## Release
# ##
# tag:
#   stage: Release
#   script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#     - echo "Tag the image for deployment"
#     - echo "Deploy to the staging repository"

# ##
# ## Deploy
# ##
# docker.hub:
#   stage: Deploy
#   script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#     - echo "Deploy the image to docker hub"
